I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 263, in script
    jump ending_5
ScriptError: could not find label 'ending_5'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 263, in script
    jump ending_5
  File "/Users/sungwoncho/Desktop/renpy-8.3.4-sdk/renpy/ast.py", line 1705, in execute
    rv = renpy.game.script.lookup(target)
  File "/Users/sungwoncho/Desktop/renpy-8.3.4-sdk/renpy/script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'ending_5'.

macOS-14.6.1-arm64-arm-64bit arm64
Ren'Py 8.3.4.24120703
madcamp 1.0
Wed Jan 15 16:00:35 2025
